package group9;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

//Generated by example maven project

/**
 * Unit test for simple App.
 */
public class CITests
{
    /**
     * Rigorous Test :-)
     */
    @Test
    public void shouldAnswerWithTrue()
    {
        assertTrue( true );
    }
}
