package group9;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;

import org.junit.Test;

//Generated by example maven project

/**
 * Unit test for simple App.
 */
public class CITests
{
    /**
     * Rigorous Test :-)
     */
    @Test
    public void shouldAnswerWithTrue()
    {
        assertTrue( false );
    }

    @Test
    public void shouldAnswerWithFalse() {
        assertFalse( true );
    }
}
